# Generated by Django 5.1.2 on 2024-11-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarefas",
            fields=[
                ("idTarefas", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "nomeTarefa",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Nome da tarefa"
                    ),
                ),
                (
                    "custo",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("dataLimite", models.DateField(verbose_name="Data de Limite")),
                (
                    "ordemDeApresentacao",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
            ],
        ),
    ]
