# Generated by Django 5.1.2 on 2024-11-13 19:07

import django.core.validators
import tarefas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0002_alter_tarefas_ordemdeapresentacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefas",
            name="custo",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="tarefas",
            name="dataLimite",
            field=models.DateField(
                validators=[tarefas.models.valideData], verbose_name="Data de Limite"
            ),
        ),
    ]
